---
name: WWW-CookieRecipesNet
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: fetch cookie recipes from http://www.cookie-recipes.net/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Data::Accessor: 0.04001
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  WWW::Mechanize: 1.34
  overload: 1.04
build_requires:
  Test::More: 0
provides:
  WWW::CookieRecipesNet:
    file: lib/WWW/CookieRecipesNet.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
